### ISSUE TITLE
Is it possible to disable week days titles below every month title?

### ISSUE THREAD

**Issue by deni1s** [andrewjapar/rangedatepicker#1]
It would be very conveniently to have a possibility to remove week days below every month. Or even start them from Monday, or customize them somehow. For example, add week titles to the top of the calendar

**Comment by andrewjapar** [comment]
It's possible! I will add an option for the next release @deni1s

**Comment by andrewjapar** [comment]
This feature has been supported on PR #5 version 0.2.2

Thanks @deni1s
