### ISSUE TITLE
  MIT or Apache or Mixed?

### ISSUE THREAD

**Issue by vsk-pvr** [andrewjapar/rangedatepicker#16]
Hi Andrew,

I can see you have distributed this awesome library under MIT in GitHub. But the files in the library are using a Apache 2 License copyright header. Can you please fix this or add some info about this is the doc.

Thanks

**Comment by andrewjapar** [comment]
Heyy @vsk-pvr 

Thanks a lot for reminding me. I've changed all headers to MIT and the license should be MIT.
